### ISSUE TITLE
Из этого цикла невозможно выйти, предлагаю цикл построить на вводе пользователя

### ISSUE THREAD

**Issue by SherlockD** [GornikMaria/travelline-practice#14]
https://github.com/GornikMaria/travelline-practice/blob/42fa6143fe5233aa89396e7757dfe45ce6c90744/homework4/BookingCar/Program.cs#L30

Например, сделать меню:
1)ввести команду
2)выйти из программы

Если пользователь вводит 2 -> выходить из цикла и заканчивать программу

**Comment by GornikMaria** [comment]
Исправила
