### ISSUE TITLE
Компонентный подход

### ISSUE THREAD

**Issue by AkshachRd** [GornikMaria/travelline-practice#18]
https://github.com/GornikMaria/travelline-practice/blob/fbbaa58f0b6854b84a141f7886e19109c956d359/homework7/lab3-boilerplate/src/App.tsx#L34-L85
В лекции рассказывал про компонентный подход. Вот ещё https://react.dev/learn/thinking-in-react.
У тебя нет ни одного компонента. React без компонентов бессмысленен.

**Comment by GornikMaria** [comment]
Исправила
