### ISSUE TITLE
Упорядочить свойства CSS

### ISSUE THREAD

**Issue by denis-bosiy** [GornikMaria/travelline-practice#3]
https://github.com/GornikMaria/travelline-practice/blob/90fe24a7448f0f43c2400149adbd3cb38c623c6f/homework5/lw5/Pages/Arithmetic/Index.cshtml#L10
NIT: Можно упорядочить свойства в CSS по определённым правилам. Обычно в хороших компаниях так делают. Можешь за пример взять правила html academy: https://codeguide.academy/html-css.html#css-order

**Comment by GornikMaria** [comment]
Исправила
