### ISSUE TITLE
Лучше перенести стили в style.css

### ISSUE THREAD

**Issue by LehaIvanov** [GornikMaria/travelline-practice#6]
Понимаю, что так тоже работает, но всё таки для нашего случая (server side rendering без css модулей) лучше все стили хранить отдельно от html, в данном случае в файле [style.css](https://github.com/GornikMaria/travelline-practice/blob/master/homework5/lw5/wwwroot/css/site.css). Причина в том, что за разбросанными по html тэгами <style> сложно следить, может получится так, что в разных html файлах окажутся css-классы с одинаковыми названиями и будут с друг другом конфликтовать.

https://github.com/GornikMaria/travelline-practice/blob/90fe24a7448f0f43c2400149adbd3cb38c623c6f/homework5/lw5/Pages/Arithmetic/Index.cshtml#L7

**Comment by GornikMaria** [comment]
Перенесла
